# Generated by Django 6.1 on 2026-08-21 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='series/')),
                ('video_url', models.URLField(blank=True, help_text="'Watch the Video' link")),
                ('audio_url', models.URLField(blank=True, help_text="'Listen to the Message' link")),
                ('apple_podcast_url', models.URLField(blank=True, verbose_name='Apple Podcast URL')),
                ('spotify_url', models.URLField(blank=True, verbose_name='Spotify URL')),
                ('soundcloud_url', models.URLField(blank=True, verbose_name='SoundCloud URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('is_current', models.BooleanField(default=False, help_text="Shown on the homepage 'Current Series' section. Only one series can be current at a time.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('speaker', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('video_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='sermons.series')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
