# Generated by Django 5.1.6 on 2026-08-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='cloudinary_id',
            field=models.CharField(blank=True, help_text='Cloudinary public_id for the audio, so it can be replaced/deleted.', max_length=255),
        ),
        migrations.AddField(
            model_name='sermon',
            name='file_size_mb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Size of the compressed audio file, shown on the 'Download {size}MB' button.", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Cloudinary secure_url of the compressed (64kbps) audio. Set automatically on upload.'),
        ),
    ]
