# Generated by Django 5.1.6 on 2026-08-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_sermon_cloudinary_id_sermon_file_size_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='is_published',
            field=models.BooleanField(default=True, help_text="Uncheck to hide this sermon from the public /sermons/ page while you're still preparing it (e.g. audio not uploaded yet). It still shows in /manage/ and /admin/ either way."),
        ),
    ]
