# Generated by Django 5.1.6 on 2026-08-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotional',
            name='is_published',
            field=models.BooleanField(default=True, help_text="Uncheck to hide this devotional from the public /devotionals/ page while you're still drafting it. It still shows in /manage/ and /admin/ either way."),
        ),
    ]
