# Generated by Django 6.1 on 2026-08-21 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('leader_name', models.CharField(max_length=150)),
                ('leader_email', models.EmailField(blank=True, help_text='If left blank, inquiries route to the general church email.', max_length=254)),
                ('meeting_day', models.CharField(blank=True, max_length=50)),
                ('meeting_time', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(blank=True, max_length=255, verbose_name='Facebook URL')),
                ('age', models.CharField(blank=True, max_length=20)),
                ('availability', models.CharField(blank=True, help_text='Day & time available', max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='groups.connectgroup')),
            ],
            options={
                'verbose_name_plural': 'group inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
